### ISSUE TITLE
Can the PowerBI Connector support Auto Refresh?

### ISSUE THREAD

**Issue by cskardon** [cskardon/Neo4jDataConnectorForPowerBi#1]
Reportedly - turning on Refresh gives:

>You can’t schedule refresh for this dataset because the following data sources currently don’t support refresh:
>Data source for Prod_Feedback
>Data source for Prod_User
>Discover Data Sources
>Query contains unknown function name: Neo4j.ExecuteCypher.

**Comment by decaxd** [comment]
facing same problem, any idea?

**Comment by cskardon** [comment]
I'm actively looking - fingers crossed it's do-able!

**Comment by Rian-II** [comment]
How is the looking going? Any feedback on supporting Auto Refresh?

**Comment by cskardon** [comment]
Feedback so far has been non-existent :/

**Comment by abcoura** [comment]
Have you tried this:

https://www.kasperonbi.com/how-to-enable-scheduled-refresh-for-your-custom-connector/

**Comment by cskardon** [comment]
No, I've not - I'll give it a try and see if it can work

**Comment by cskardon** [comment]
I've added a [1.4.0-beta](https://github.com/cskardon/Neo4jDataConnectorForPowerBi/releases/tag/1.4.0-beta) release for people to try, if you can, that'd be great, as I don't seem to have the options in my instance to see.

**Comment by abcoura** [comment]
I've tested this new version and received the following error. 
"Fail to update credentials from dataset: 0 arguments were passed to a function which expects between 1 and 7"
One parameter on the conector is needed at least. Maybe this can help.
https://docs.microsoft.com/en-us/power-query/handlinggatewaysupport#example-connector-with-required-parameters

**Comment by cskardon** [comment]
Thanks @abcoura 

I'll have a look and see - one of my problems is that I'm not 100% sure how to test this - is it something I can test in PowerBI Desktop, without needing to set anything else up? If so - how!?! :)

**Comment by cskardon** [comment]
On that, I think this release: [1.4.0-beta-2](https://github.com/cskardon/Neo4jDataConnectorForPowerBi/releases/tag/1.4.0-beta-2) solves the problem... but again, please try and let me know!

**Comment by abcoura** [comment]
> Thanks @abcoura
> 
> I'll have a look and see - one of my problems is that I'm not 100% sure how to test this - is it something I can test in PowerBI Desktop, without needing to set anything else up? If so - how!?! :)

I believe you cant test it from PBI desktop. You will need to publish you PBIX and try to schedule a refresh. 
https://www.poweredsolutions.co/2018/04/23/refreshing-a-power-bi-custom-connector-in-the-cloud/

**Comment by abcoura** [comment]
Just tested. Still Not working. I've translated the error message:
Falha ao atualizar as credenciais da fonte de dados: 
( Fail to update Data Source Credentials: )
ID da atividade ( Activity ID):	57d2e481-6587-4502-9c3e-9e00a629786b
Código de status (Status Code):	400
Hora (Time) :	Wed Jul 15 2020 09:36:27 GMT-0300
Versão do serviço (Service Version):	13.0.13860.51
Versão do Cliente (Client Version):	2007.1.01830-train
Cluster URI:	https://wabi-south-central-us-redirect.analysis.windows.net/

This error is NOT very helpfull as you can see.

**Comment by cskardon** [comment]
Ha, no, is it anything to do with needing to add the Neo4j source onto the PowerBI gateway? (from: [this post](https://community.powerbi.com/t5/Service/Failed-to-update-data-source-credentials/m-p/508147#M52531) )?

**Comment by abcoura** [comment]
The conector shows up in my Gateway so i dont think is actually a real problem. And you can test it if you want. Using a free account you can publish a PBI and try to refresh it from the app.powerbi.com 
If you want you can send me an email abcoura@hotmail.com and we can talk more. Thanks for all the help.

**Comment by abcoura** [comment]
> Ha, no, is it anything to do with needing to add the Neo4j source onto the PowerBI gateway? (from: [this post](https://community.powerbi.com/t5/Service/Failed-to-update-data-source-credentials/m-p/508147#M52531) )?

@cskardon are you going to try any other aproaches to the Connection test on the conector? Im still fighting with it.

**Comment by cskardon** [comment]
At the moment, I'm super busy with work, I'd like to get this work - the problem is the TestConnection as far as I can see I've done what needs to be done, but until I get the time to set things up and play with it properly, I can't be sure.

**Comment by cskardon** [comment]
OK, update, so far I've got a personal gateway setup which PBI is saying is connected, but it's not letting me set the credentials. It's not showing the proper connection dialog, so there is no way to choose how to connect.

I've tried both the personal gateway, and the enterprise but to no avail. There is the possibility this is due to the way my internet is connected, as I believe I have a double NAT situation which might be throwing the gateway, _buuuut_ it is saying it's connected.

I am unable to add Neo4j as a data source either, as the gateway won't show it as an option, though I don't know why.

**Comment by cskardon** [comment]
I'm back having a look at this now, I've managed to get my connection to the gateway working (I think), I can schedule a refresh:

![image](https://user-images.githubusercontent.com/1875805/98008784-c2a4ce00-1dec-11eb-8ff8-26ce5f4414ec.png)

But this isn't auto-refresh right?

It seems that might be tied to `DirectQuery` connectors - which looks like I might need to implement a few methods which I've not: https://github.com/microsoft/DataConnectors/issues/246#issuecomment-555638745

So I'm going to see if I can find what needs to be done for DQ to work

**Comment by abcoura** [comment]
Great News!!! I will try it and will tell you what happend, thanks for the effort.
I think this will solve the update problem.

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

[cid:logo-azul-semgrafico_8b067453-4d26-4ebe-9a4b-fe617ed975b5.png]
Adriano Coura
Data Engineer
31 98759 6188
adriano.coura@qdois.com.br <mailto:adriano.coura@qdois.com.br>
qdois.com.br <https://qdois.com.br>
        [cid:border-azul-alto_b55e2015-aaea-4815-87fc-8fba98b4d669.png]
De: Chris Skardon<mailto:notifications@github.com>
Enviado:terça-feira, 3 de novembro de 2020 12:55
Para: cskardon/Neo4jDataConnectorForPowerBi<mailto:Neo4jDataConnectorForPowerBi@noreply.github.com>
Cc:Adriano Coura<mailto:adriano.coura@qdois.com.br>; Mention<mailto:mention@noreply.github.com>
Assunto: Re: [cskardon/Neo4jDataConnectorForPowerBi] Can the PowerBI Connector support Auto Refresh? (#1)


I'm back having a look at this now, I've managed to get my connection to the gateway working (I think), I can schedule a refresh:

[https://user-images.githubusercontent.com/1875805/98008784-c2a4ce00-1dec-11eb-8ff8-26ce5f4414ec.png]<https://user-images.githubusercontent.com/1875805/98008784-c2a4ce00-1dec-11eb-8ff8-26ce5f4414ec.png>

But this isn't auto-refresh right?

It seems that might be tied to DirectQuery connectors - which looks like I might need to implement a few methods which I've not: microsoft/DataConnectors#246 (comment)<https://github.com/microsoft/DataConnectors/issues/246#issuecomment-555638745>

So I'm going to see if I can find what needs to be done for DQ to work

**Comment by gghugtyal** [comment]
> 
> 
> I'm back having a look at this now, I've managed to get my connection to the gateway working (I think), I can schedule a refresh:
> 
> ![image](https://user-images.githubusercontent.com/1875805/98008784-c2a4ce00-1dec-11eb-8ff8-26ce5f4414ec.png)
> 
> But this isn't auto-refresh right?
> 
> It seems that might be tied to `DirectQuery` connectors - which looks like I might need to implement a few methods which I've not: [microsoft/DataConnectors#246 (comment)](https://github.com/microsoft/DataConnectors/issues/246#issuecomment-555638745)
> 
> So I'm going to see if I can find what needs to be done for DQ to work

Hi,

I have been successfully using the Neo4j connector in the Power BI desktop app. I published a neo4j based report in my Office365 Power BI Service. I need to setup the scheduled refresh for the neo4j dataset. I created an on-premise power bi gateway and added the custom neo4j connector in it as well. In the Power bi service, when you add the data source to your gateway, do you see the neo4j custom connector in the data source list? I am not able to add the neo4j data source with my gateway? Am I missing something?

Thanks,

**Comment by cskardon** [comment]
Honestly - I'm afraid I can't remember, I'm not even sure which gateway I was using at that point - I'm not sure what you would be missing - it _sounds_ like you've done what I did, and I think I did see the connector in the source.

Are you using the enterprise gateway or the personal one?

**Comment by gghugtyal** [comment]
> 
> 
> Honestly - I'm afraid I can't remember, I'm not even sure which gateway I was using at that point - I'm not sure what you would be missing - it _sounds_ like you've done what I did, and I think I did see the connector in the source.
> 
> Are you using the enterprise gateway or the personal one?

Hi,

I tried both gateway types. In the case of Enterprise gateway, I am seeing one of the data source typ options as "Execute Cypher - Output", though I was assuming that I should be seeing the type as Neo4j, nevertheless I tried using "Execute Cypher - Output" type, it asks me for cypher, username and password, doesn't show scheme, database name, port etc. I gave username and password and getting exception as "The provider is not support or due to invalid data source. Please check the data source connection string. The given data source kind is not supported. Data source kind: Neo4j."

When I used the gateway in personal mode, I am getting this error on adding data source "Failed to update data source credentials: The given data source kind is not supported. Data source kind: Neo4j"

Did you face this?

Thanks

**Comment by cskardon** [comment]
It's possible, let's try to get this working - first off, which version of the connector are you using?

**Comment by gghugtyal** [comment]
> 
> 
> It's possible, let's try to get this working - first off, which version of the connector are you using?

I am using the latest version i.e. 1.4.0

**Comment by cskardon** [comment]
Just under two years, and I think I have this working for the personal gateway.

Please if you can (and indeed still care) try the `1.5.0-beta-1` release

https://github.com/cskardon/Neo4jDataConnectorForPowerBi/releases/tag/1.5.0-beta-1

The biggest difference here is the need to supply all the details, no more optional ones.

**Comment by cskardon** [comment]
The [`2.1.0`](https://github.com/cskardon/Neo4jDataConnectorForPowerBi/releases/tag/2.1.0) release works with both the Enterprise and Personal gateways.

Unfortunately, dropdowns don't seem to work for the Enterprise gateway so everything is now just text entry.
