### ISSUE TITLE
Compatibility with v4.0

### ISSUE THREAD

**Issue by Legolash2o** [cskardon/Neo4jDataConnectorForPowerBi#2]
It doesn't seem to be compatible with Neo4j v4.0.3. I think you'd need a database text box with the default being 'neo4j'.

**Comment by cskardon** [comment]
What version are you using?
`1.2` has this:

![image](https://user-images.githubusercontent.com/1875805/80081523-f902b600-854a-11ea-9e9d-79fbc0209ccb.png)

**Comment by Legolash2o** [comment]
Hey, 1.0. I couldn't see the download link for 1.2

**Comment by cskardon** [comment]
OK, all the releases are at: https://github.com/cskardon/Neo4jDataConnectorForPowerBi/releases

**Comment by cskardon** [comment]
PS. I've updated the readme file to link to the releases page as well.
