### ISSUE TITLE
Power Bi Connector doesn't work on Neo4j v4.0

### ISSUE THREAD

**Issue by dasg7** [cskardon/Neo4jDataConnectorForPowerBi#3]
Trying to connect from Power Bi to a server running the recent Neo4j 4.0 version, with the Power Bi connector v1.0, throws the following error:

"DataSource.Error: Web.Contents failed to get contents from 'http://ip:7474/db/data/transaction/commit' (415): 

Unsupported Media Type

Details:
    DataSourceKind=Neo4j
    DataSourcePath={"cypher":"query;"}
    Url=http://ip:7474/db/data/transaction/commit

**Comment by dasg7** [comment]
My bad, I never updated the connector to the new versions.

**Comment by cskardon** [comment]
Easiest form of bug to solve! :)
